/* eslint-disable sonar/no-duplicate-string -- shut up */

import style from "@isentinel/eslint-config";

import perfectionist from "eslint-plugin-perfectionist";

export default style(
	{
		formatters: {
			css: true,
			graphql: true,
			html: true,
			lua: false,
			markdown: false,
			prettierOptions: {
				arrowParens: "always",
				bracketSameLine: false,
				bracketSpacing: true,
				checkIgnorePragma: false,
				embeddedLanguageFormatting: "auto",
				endOfLine: "auto",
				experimentalOperatorPosition: "end",
				experimentalTernaries: false,
				filepath: undefined,
				htmlWhitespaceSensitivity: "css",
				insertPragma: false,
				jsxSingleQuote: false,
				objectWrap: "preserve",
				printWidth: 120,
				proseWrap: "preserve",
				quoteProps: "as-needed",
				requirePragma: false,
				semi: true,
				singleQuote: false,
				tabWidth: 4,
				trailingComma: "all",
				useTabs: true,
				vueIndentScriptAndStyle: false,
			},
		},
		gitignore: true,
		ignores: [
			"**/node_modules/**",
		],
		jsonc: true,
		jsx: true,
		markdown: false,
		perfectionist: {
			customClassGroups: [],
		},
		plugins: {
			perfectionist,
		},
		pnpm: false,
		react: true,
		roblox: true,
		rules: {
			"antfu/consistent-list-newline": "off",
			"antfu/no-top-level-await": "off",
			"arrow-style/arrow-return-style": "off",
			"comment-length/limit-multi-line-comments": "error",
			"comment-length/limit-single-line-comments": "error",
			"comment-length/limit-tagged-template-literal-comments": "error",
			curly: "off",
			"id-length": "off",
			"sonar/no-nested-conditional": "off",
			"max-lines": [
				"warn",
				{
					max: 700,
				},
			],
			"max-lines-per-function": "off",
			"no-inline-comments": "off",
			"no-restricted-syntax": "off",
			"no-throw-literal": "off",
			"perfectionist/sort-classes": [
				"warn",
				{
					groups: [

						"static-property",
						"protected-static-property",
						"private-static-property",
						"property",
						"protected-property",
						"private-property",

						"protected-static-accessor-property",
						"private-static-accessor-property",
						"protected-accessor-property",
						"private-accessor-property",

						["get-method", "set-method"],
						"protected-static-get-method",
						"protected-static-set-method",
						"private-static-get-method",
						"private-static-set-method",
						"protected-get-method",
						"protected-set-method",
						"private-get-method",
						"private-set-method",
						"static-method",
						"protected-static-method",
						"private-static-method",
						"method",
						"constructor",
						"protected-method",
						"private-method",
					],
					order: "asc",
				},
			],
			"perfectionist/sort-objects": [
				"warn",
				{
					customGroups: {
						id: "^id$",
						name: "^name$",
						callbacks: ["\b(on[A-Z][a-zA-Z]*)\b"],
						reactProps: ["^children$", "^ref$"],
					},
					groups: ["id", "name", "unknown", "reactProps"],
					order: "asc",
					partitionByComment: "^Part:\\*\\*(.*)$",
					type: "natural",
				},
			],
			"roblox/lua-truthiness": "error",
			"roblox/no-user-defined-lua-tuple": "off",
			"sonar/cognitive-complexity": "off",
			"sonar/cyclomatic-complexity": ["off", { threshold: 10 }],
			"sonar/no-commented-code": "off",
			"sonar/no-nested-incdec": "off",
			"style/padding-line-between-statements": "off",
			"test/require-hook": "off",
			"test/valid-expect": "off",
			"ts/explicit-member-accessibility": [
				"error",
				{
					accessibility: "explicit",
				},
			],
			"ts/no-empty-function": "off",
			"ts/no-empty-object-type": "off",
			"ts/no-non-null-assertion": "off",
			"ts/no-require-imports": "off",
			"ts/no-unnecessary-condition": "off",
			"ts/no-unsafe-argument": "off",
			"ts/no-unsafe-assignment": "off",
			"ts/no-unsafe-call": "off",
			"ts/no-unsafe-member-access": "off",
			"ts/no-unsafe-return": "off",
			"ts/only-throw-error": "off",
			"ts/prefer-promise-reject-errors": "off",
			"ts/strict-boolean-expressions": "off",
			"ts/switch-exhaustiveness-check": "off",
			"ts/unbound-method": "off",
			"unicorn/catch-error-name": [
				"error",
				{
					name: "error",
				},
			],
			"unicorn/consistent-destructuring": "off",
			"unicorn/no-keyword-prefix": "off",
			"unicorn/no-useless-undefined": ["error", { checkArguments: false, checkArrowFunctionBody: false }],
			"unicorn/prefer-single-call": "off",
			"unicorn/switch-case-braces": "off",
			"ts/no-unused-vars": "off",
			"ts/no-unused-expressions": "off",
			"ts/no-unnecessary-type-assertion": "off",
			"new-cap": "off",
			"roblox/misleading-lua-tuple-checks": "off",
			"unicorn/filename-case": ["error", { case: "camelCase" }],
			"ts/no-unnecessary-type-parameters": "off",
			"unicorn/prefer-switch": "off",
			"better-max-params/better-max-params": "off",
		},
		spellCheck: false,
		stylistic: {
			indent: "tab",
			jsx: true,
			quotes: "double",
			semi: true,
		},
		test: true,
		toml: false,
		type: "package",
		typescript: {
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
			tsconfigPath: "./tsconfig.json",
			typeAware: true,
		},
	},
	{
		"files": ["src/dataType.ts"],
		"rules": {
			"unicorn/prevent-abbreviations": "off"
		}
	}
);
